#No language required so just use ruby to avoid warnings in travis yml linter
language: ruby
dist: trusty
sudo: required

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - sudo apt-get -qq update
    #calibre required for gitbook pdf
  - sudo apt-get install -y calibre

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install -g gitbook-cli

script:
  - openssl aes-256-cbc -K $encrypted_3312804ce423_key -iv $encrypted_3312804ce423_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
  - ssh-add deploy-key
  - gitbook install
  - gitbook build
#    - gitbook pdf ./ ./stroom-docs.pdf
  - git fetch origin gh-pages:gh-pages
  - git worktree add build gh-pages
  - rsync -ar --delete --exclude '.git' ./_book/ ./build/
  - pushd build
# TODO could fail the build if we find un-converted markdown files
  - echo "Finding un-converted markdown files" && find . -name "*.md"
  - git config user.name "Automatic Publish"
  - git config user.email "stroom-docs_travis-ci"
  - git pull
  #- git add -all
  #- git commit -m 'Update gitbook generated html from master'
  #- git push
# TODO add, commit and push to git
  - popd

# TODO release the pdf to a release tag, e.g. 'latest', updating the artifact
