#No language required so just use ruby to avoid warnings in travis yml linter
language: node_js
dist: trusty
sudo: required

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - sudo apt-get -qq update
    #calibre required for gitbook pdf
  - sudo apt-get install -y calibre

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install -g gitbook-cli

script:
  - openssl aes-256-cbc -K $encrypted_3312804ce423_key -iv $encrypted_3312804ce423_iv -in deploy-key.enc -out ~/.ssh/deploy-key -d
  - chmod 600 ~/.ssh/deploy-key
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/deploy-key
  - cp ssh_config ~/.ssh/config
  - gitbook install
  - gitbook build
#    - gitbook pdf ./ ./stroom-docs.pdf
  - git fetch origin gh-pages:gh-pages
  - git worktree add build gh-pages
  - rsync -ar --delete --exclude '.git' ./_book/ ./build/
  - pushd build
# TODO could fail the build if we find un-converted markdown files
  - echo "Finding un-converted markdown files" && find . -name "*.md"
  - git remote set-url origin git@github.com:gchq/stroom-docs.git
  - git config --global user.name "$GIT_USER"
  - git config --global user.email "$GIT_EMAIL"
  - git status
  - git add -all
  - git commit -m 'Automated update of gitbook generated html from master'
  - git push --set-upstream origin gh-pages
# TODO add, commit and push to git
  - popd

# TODO release the pdf to a release tag, e.g. 'latest', updating the artifact

branches:
  only:
    - master
